import Head from 'next/head';
import Image from 'next/image';
import Navbar from './components/navbar/nav';
import Footer from './components/footer/Footer';
import { Inter } from 'next/font/google';
import { Container, CssBaseline } from '@mui/material';
import styles from '@/styles/Home.module.css';
import { ThemeProvider, createTheme } from '@mui/material/styles';
const inter = Inter({ subsets: ['latin'] });

const theme = createTheme();
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>   
      <ThemeProvider theme={theme}>
      <CssBaseline />

      <Navbar />

      <Container component="main" className={`${styles.main} ${inter.className}`} maxWidth="md">
        {/* Your existing content here */}

        {/* Example profile image */}
        <div className={styles.profileImageContainer}>
          <Image
            src="/profile-image.jpg"
            alt="Profile Image"
            width={100}
            height={100}
          />
        </div>

        {/* Your existing content here */}
      </Container>

      <Footer />
      </ThemeProvider>
    </>
  );
}
