import Head from 'next/head';
import { router } from 'next/router';
import React from 'react';

export default function Home() {
  React.useEffect(() => {
    // Redirect to login page
    router.push('./auth/login_register');
  }, []);
  return (
    <>
      <Head>
        <title>Event Managemant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>   

    

    </>
  );
}
